version: '3'

services:
  db:
    container_name: db
    image: "postgres:13"
    env_file:
      - .env
    networks:
      - sochat
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: "./backend"
    env_file:
      - .env
    networks:
      - sochat
    depends_on:
      - db
    expose:
      - "5000"
      

  frontend:
    container_name: frontend
    networks:
      - sochat
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "1337:80"
    depends_on:
      - backend

  ssh-client:
    build:
      context: ./ssh-client
      dockerfile: Dockerfile
    networks:
      - sochat
    depends_on:
      - backend
    ports:
      - "2222:22"
  
volumes:
  pgdata:

networks:
  sochat:
    driver: bridge
