version: '3'

services:
  db:
    container_name: db
    image: "postgres:13"
    env_file:
      - .env
    networks:
      - sochat
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 100M

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: "./backend"
    env_file:
      - .env
    networks:
      - sochat
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 200M
      

  frontend:
    container_name: frontend
    networks:
      - sochat
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "1337:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.02'
          memory: 100M

  ssh-client:
    build:
      context: ./ssh-client
      dockerfile: Dockerfile
    networks:
      - sochat
    depends_on:
      - backend
    ports:
      - "2222:22"
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 100M
  
volumes:
  pgdata:

networks:
  sochat:
    driver: bridge
